### ISSUE TITLE
SAVE_FILE bugs in kpf_photon_noise_estimate.pro

### ISSUE THREAD

**Issue by smmills** [California-Planet-Search/KPF-etc#1]
If QUIET=1 and SAVE_FILE=1, the save file only contains zeros.
In any case, the wavelengths in the saved file seem incorrect?

**Comment by shalverson** [comment]
Fixed - thanks!

This was printing the echelle order number, rather than the order wavelength, in the first column of the text file (now fixed).

'QUIET' was removed - no terminal printing at all now.
